# Generated by Django 5.0.6 on 2024-07-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
    ]
